language: java

cache: 
    directories:
        - "$HOME/.m2/repository"

services: 
    - docker

script: 
    - mvn clean verify
    
    - docker build -t "$DOCKER_USERNAME"/sample-cpe:api sample-application-http-api-server
    - docker build -t "$DOCKER_USERNAME"/sample-cpe:db sample-application-db-changelog-job

    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push "$DOCKER_USERNAME"/sample-cpe:api
    - docker push "$DOCKER_USERNAME"/sample-cpe:db