language: java

cache: 
    directories:
        - "$HOME/.m2/repository"

services: 
    - docker

script: 
    - mvn clean verify
    
    - docker build -t kyalarys/sample-cpe:api sample-application-http-api-server
    - docker build -t kyalarys/sample-cpe:db sample-application-db-changelog-job

    - docker login -u kyalarys -p $DOCKER_HUB_SECRET
    - docker push kyalarys/sample-cpe:api
    - docker push kyalarys/sample-cpe:db